interface Props {
  oldHash: string;
  newHash: string;
}

/** Visualise the 64-bit perceptual fingerprint as an 8×8 dot grid for
 *  each side, then a third grid marking the bits that differ. Each dot
 *  is one bit; set bits are the copper accent, cleared bits are dim.
 *  The diff grid highlights only the bits that changed.
 *
 *  This is alt-only. The hash is generated by alt-diff::perceptual on
 *  the PNG's inflated IDAT payload — git has no equivalent. Surfacing
 *  it here is the most direct way to show "alt sees inside the PNG;
 *  git does not." */
export function FingerprintGrid({ oldHash, newHash }: Props) {
  const o = parseHash(oldHash);
  const n = parseHash(newHash);
  const diff = o.map((b, i) => b ^ n[i]);

  return (
    <div className="px-4 py-3 grid grid-cols-1 md:grid-cols-3 gap-4 border-b border-border-default">
      <Grid title="before" hash={oldHash} bits={o} />
      <Grid title="after" hash={newHash} bits={n} />
      <Grid title="bits flipped" bits={diff} highlight />
    </div>
  );
}

function Grid({
  title,
  hash,
  bits,
  highlight = false,
}: {
  title: string;
  hash?: string;
  bits: number[];
  highlight?: boolean;
}) {
  const setCount = bits.reduce((acc, b) => acc + b, 0);
  return (
    <div className="bg-canvas-inset/40 border border-border-muted rounded-md px-3 py-3">
      <div className="flex items-center justify-between mb-2 text-[10px] font-mono uppercase tracking-[0.22em]">
        <span className={highlight ? "text-warm" : "text-fg-subtle"}>
          {title}
        </span>
        {hash ? (
          <span className="text-fg-muted">{hash}</span>
        ) : (
          <span className="text-warm">{setCount} / 64</span>
        )}
      </div>
      <div className="grid grid-cols-8 gap-1 w-fit mx-auto">
        {bits.map((bit, i) => (
          <span
            key={i}
            className={`w-3 h-3 rounded-sm ${
              highlight
                ? bit
                  ? "bg-warm shadow-[0_0_4px_rgba(232,168,124,0.6)]"
                  : "bg-canvas-subtle border border-border-muted"
                : bit
                  ? "bg-warm"
                  : "bg-canvas-subtle border border-border-muted"
            }`}
          />
        ))}
      </div>
    </div>
  );
}

function parseHash(hex: string): number[] {
  // 16 hex chars → 64 bits → returned LSB-first so bit i in the array
  // corresponds to bit i in the u64. Layout in the grid is top-left
  // (bit 0) → bottom-right (bit 63), row by row.
  const out: number[] = [];
  const cleaned = hex.padStart(16, "0").slice(-16);
  for (let i = 0; i < cleaned.length; i++) {
    const nibble = parseInt(cleaned[i], 16);
    for (let b = 3; b >= 0; b--) {
      out.push((nibble >> b) & 1);
    }
  }
  return out;
}
